#!/bin/bash -x

# set keyboard layout to uk
setxkbmap -model thinkpad -layout gb

# set wallpaper
feh --bg-fill --no-fehbg $HOME/.config/wallpaper/default

# start ssh-agent
eval `ssh-agent`

# launch bspwm
exec bspwm
