#! /bin/sh
bspc rule -r "*"

# Autostart
picom -b --experimental-backends &
launchpolybar &

# Monitors
bspc monitor -d I II III IV V VI VII VIII IX X

# Window manager settings
bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color = "#4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color = "#d8dee8"
bspc config presel_feedback_color = "#5e81ac"
bspc config urgent_border_color = "#dd2727"

bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 16