#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# configuration
bspc config border_width         2
bspc config window_gap          16
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false

# colour settings
bspc config focused_border_color = "#d8dee8"
bspc config focused_border_color = "#2f343f"