#! /bin/sh
bspc rule -r "*"

# X settings
xset r rate 210 40
xsetroot -cursor_name left_ptr

# Autostart
dunst &
$HOME/.fehbg &
$HOME/.config/polybar/launchpolybar &

# Monitors
bspc monitor -d 1 2 3 4 5 6 7 8 9 0
bspc monitor DP1-1 -n 1 -d IV V VI
bspc monitor DP1-2 -n 2 -d VII VIII IX X

# Window manager settings
bspc config normal_border_color "#282828"
bspc config active_border_color "#727272"
bspc config focused_border_color "#636363"
bspc config presel_feedback_color "#6272a4"

bspc config border_width 4
bspc config window_gap 0
bspc config split_ratio 0.55
