#! /bin/sh
bspc rule -r "*"

# Autostart
xset r rate 210 40
dunst &
$HOME/.fehbg &
$HOME/.config/polybar/launchpolybar &

# Monitors
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# Window manager settings
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color = "#4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color = "#d8dee8"
bspc config presel_feedback_color = "#5e81ac"
bspc config urgent_border_color = "#dd2727"

bspc config border_width 4
bspc config window_gap 0
