#!/bin/bash

# A simple script to count the amount of packages that need updating
pkgCount=$(xbps-install -Mun | wc -l)

if [ $pkgCount -gt 0 ]; then
    echo "ﮮ $pkgCount"
else
    echo "ﮮ $pkgCount"
fi
