# .bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

# add $HOME/.bin to PATH
if [ -d "$HOME/.bin" ] ; then
  PATH="$PATH:$HOME/.bin"
fi

export TERM=xterm-256color
export GOPATH=$HOME/go
