#!/bin/sh
# Launch an instance of Polybar

# Terminate the process if its already running
killall -q polybar

# Wait until its gracefully shut down
while pgrep -u $UID -x polybar > /dev/null; do sleep 1; done;

# Launch Polybar using default config
polybar example &